#!/bin/bash

# nounset: undefined variable outputs error message, and forces an exit
set -u
# errexit: abort script at first error
set -e
# print command to stdout before executing it:
set -x

# Provided environmental variables:
# $OPENFIDO_INPUT: A directory containing any input files provided via the
# OpenFido website.
#
# $OPENFIDO_OUTPUT: An output directory. Any artifacts generated by your tasks
# should be moved into this directory.

# sample implementation:
ls $OPENFIDO_INPUT > $OPENFIDO_OUTPUT/inputfiles.txt
